version: '3.8'

services:
  app:
    container_name: telegrambotwar
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9999:9999" # Экспонируем порт приложения
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:7766/library_database
      SPRING_DATASOURCE_USERNAME: library_user
      SPRING_DATASOURCE_PASSWORD: library_password
    depends_on:
      - db # Указываем зависимость от сервиса с базой данных
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    ports:
      - "7766:7766" # Экспонируем порт PostgreSQL
    environment:
      POSTGRES_DB: library_database
      POSTGRES_USER: library_user
      POSTGRES_PASSWORD: library_password
    command:
      - "postgres"
      - "-c"
      - "port=7766"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data: # Хранилище данных для PostgreSQL

networks:
  app-network: # Общая сеть для взаимодействия между сервисами
